### ISSUE TITLE
error in "filterViralOverhangsAndGenerateSeq.pl" and "filterOverhangAlignments.pl" perl script

### ISSUE THREAD

**Issue by Jigyasa3** [njdbickhart/RumenLongReadASM#1]
Hey @njdbickhart thank you for such an interesting analysis! 
I was trying the perl scripts in /viralAnalysisScripts/ folder, and I am running into some syntax error as shown below.

Error1-
`syntax error at /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterViralOverhangsAndGenerateSeq.pl line 7, near "chomp"
Global symbol "$usage" requires explicit package name (did you forget to declare "my $usage"?) at /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterViralOverhangsAndGenerateSeq.pl line 10.
Bareword "STDIN" not allowed while "strict subs" in use at /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterViralOverhangsAndGenerateSeq.pl line 16.
Execution of /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterViralOverhangsAndGenerateSeq.pl aborted due to compilation errors.`

Error2-
`syntax error at /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterOverhangAlignments.pl line 37, near "))"
Global symbol "$keys" requires explicit package name (did you forget to declare "my $keys"?) at /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterOverhangAlignments.pl line 40.
Global symbol "$keys" requires explicit package name (did you forget to declare "my $keys"?) at /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterOverhangAlignments.pl line 40.
syntax error at /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterOverhangAlignments.pl line 41, near "}"
Execution of /bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAnalysisScripts/filterOverhangAlignments.pl aborted due to compilation errors.`

Any suggestions what might be happening?

**Comment by njdbickhart** [comment]
Hello @Jigyasa3 , I apologize for these errors. I think that they cropped up during a mistranslation from my original source code when I packaged things for the pipeline. 

I just corrected the mistakes in these scripts and the createHiCLinktabFile.pl script. A "perl -c" suggests that the syntax is correct and that all variables are following strict rules. Let me know if you run into any other errors while using them!

**Comment by Jigyasa3** [comment]
Hey @njdbickhart 

Thank you for debugging!
I am running into some new error now. The code says that it has written to file, but there is no output "ec_virus_long_read_overhangs" file generated.

Code-
`perl ${SOFT_DIR2}/selectLikelyViralOverhangs.pl ec_virus_long_read_alignments.paf ec_virus_long_read_overhangs

perl ${SOFT_DIR2}/filterViralOverhangsAndGenerateSeq.pl ec_virus_long_read_overhangs.bed ${IN_DIR}/SRR8266664_subreads.fasta 150 ec_virus_long_read_overhangs.fa
`

Error-
`Finished writing to file!
[M::mm_idx_gen::95.114*1.00] collected minimizers
[M::mm_idx_gen::126.587*1.00] sorted minimizers
[M::main::126.587*1.00] loaded/built the index for 1660461 target sequence(s)
[M::mm_mapopt_update::128.754*1.00] mid_occ = 185
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 1660461
[M::mm_idx_stat::130.501*1.00] distinct minimizers: 170320486 (42.95% are singletons); average occurrences: 3.016; average spacing: 7.787; total length: 4000243979
ERROR: failed to open file 'ec_virus_long_read_overhangs.fa': No such file or directory
ERROR: failed to map the query file
`

The "c_virus_long_read_alignments.paf" is generated in the previous step
 `734K Jul 31 14:35 ec_virus_long_read_alignments.paf` .

**Comment by njdbickhart** [comment]
Hello @Jigyasa3 , in the other issue report, it sounded like you had a file permission mix-up. Is that the case here for the output folder? If not I can take a closer look at the code.

**Comment by Jigyasa3** [comment]
Hey @njdbickhart!

The perl script is still not working. It says that output is generated, but no file gets generated. 

The code-
`perl filterViralOverhangsAndGenerateSeq.pl ec_virus_long_read_overhangs.subread.bed SRR8266664_subreads.fasta 150 ec_virus_long_read_overhangs.fa
Finished writing to file!
`
But the file doesn't exist. I am running it in the correct folder this time..any suggestions? The python code works, so I am in no hurry. Thank you so much for all the help!

**Comment by njdbickhart** [comment]
Hello @Jigyasa3 ,

OK, there could be a few possible reasons here. 

1. Can you print the output of a " `head ec_virus_long_read_overhangs.subread.bed `"? If that file is empty, you won't generate the output.
2. Can you also make sure that samtools is in your $PATH by typing " `which samtools` "?

Let me know if both the file is complete and samtools is present and I will try to find another reason why this might not be working.

**Comment by Jigyasa3** [comment]
Hey @njdbickhart 

Thank you for replying!
Here is how the bed file looks like-
`$ head ec_virus_long_read_overhangs.subread.bed
SRR8266664.278  0       5711    k127_1381788
SRR8266664.1707 0       10959   k127_846621
SRR8266664.1707 0       3259    k127_596715
SRR8266664.1707 10721   19170   k127_596715
SRR8266664.1708 0       655     k127_274056
SRR8266664.1708 16971   20091   k127_596715
SRR8266664.1708 0       11732   k127_1205890
SRR8266664.5809 2904    8186    k127_1112272
SRR8266664.5809 0       3695    k127_3395283
SRR8266664.9884 0       1313    k127_161113
`

And the samtools version loaded is-
`$ which samtools
/apps/free81/samtools/1.9/bin/samtools`

I was wondering, the bed file that I have generated contains less than 500 subreads, could that be causing the error? The Perl script (I have limited perl syntax knowledge) has this condition `if(scalar(@list) >= 500)`, do you think that's leading to an empty output file.

`$ wc -l *bed
485 ec_virus_long_read_overhangs.subread.bed`

Thanks again for helping debug!
